import { encryptEvidence, sha256Hex, type EncryptedPayload } from './crypto';
import { desEncrypt, type DesResult } from './desCrypto';
import { bytesToBase64, base64ToBytes } from './steganography';

// ===== CipherView Report Generator =====
// Generates a forensic incident report, encrypts it with the analyst's
// chosen algorithm (AES-256-GCM or DES-ECB), and produces a cipher
// visualization. The ciphered output feeds into VoxCrypt for audio
// steganography.

export type CipherAlgorithm = 'AES-256-GCM' | 'DES';

export interface IncidentReport {
  incidentId: string;
  attackType: string;
  mitre: string;
  severity: string;
  threatScore: number;
  riskScore: number;
  timestamp: string;
  aiSummary: string;
  matchedLogs: string[];
  recommendedActions: string[];
  evidenceHash?: string;
}

export interface CipherReportResult {
  algorithm: CipherAlgorithm;
  plaintext: string;
  cipherB64: string;       // base64 ciphertext (for visualization + stego)
  ivB64?: string;          // AES only
  saltB64?: string;        // AES only
  hash: string;            // SHA-256 integrity hash
  keyBits: number;
  blockSize: number;
  createdAt: string;
  // Visualization data
  blockPreview: { index: number; plainHex: string; cipherHex: string }[];
  entropyScore: number;    // 0-100, randomness of ciphertext
}

export function buildIncidentReport(incident: {
  id: string;
  attackType: string;
  mitre: string;
  severity: string;
  threatScore: number;
  riskScore: number;
  timestamp: string;
  aiSummary: string;
  matchedLogs?: string[] | number;
  recommendedActions?: string[];
  evidenceHash?: string;
}): IncidentReport {
  return {
    incidentId: incident.id,
    attackType: incident.attackType,
    mitre: incident.mitre,
    severity: incident.severity,
    threatScore: incident.threatScore,
    riskScore: incident.riskScore,
    timestamp: incident.timestamp,
    aiSummary: incident.aiSummary,
    matchedLogs: Array.isArray(incident.matchedLogs) ? incident.matchedLogs : [],
    recommendedActions: incident.recommendedActions || [],
    evidenceHash: incident.evidenceHash,
  };
}

export function reportToText(report: IncidentReport): string {
  const lines = [
    '================================================',
    '  THREATZERO SENTINEL X — FORENSIC INCIDENT REPORT',
    '================================================',
    '',
    `Incident ID     : ${report.incidentId}`,
    `Attack Type     : ${report.attackType}`,
    `MITRE Technique : ${report.mitre}`,
    `Severity        : ${report.severity}`,
    `Threat Score    : ${report.threatScore}/99`,
    `Risk Score      : ${report.riskScore}/99`,
    `Timestamp       : ${report.timestamp}`,
    `Evidence Hash   : ${report.evidenceHash || 'N/A'}`,
    '',
    '--- AI ANALYSIS SUMMARY ---',
    report.aiSummary,
    '',
    '--- MATCHED LOGS ---',
    ...(report.matchedLogs.length > 0
      ? report.matchedLogs.map((l, i) => `  [${i + 1}] ${l}`)
      : ['  No matched logs recorded.']),
    '',
    '--- RECOMMENDED RESPONSE ACTIONS ---',
    ...(report.recommendedActions.length > 0
      ? report.recommendedActions.map((a, i) => `  ${i + 1}. ${a}`)
      : ['  No actions recorded.']),
    '',
    '================================================',
    '  END OF REPORT — GENERATED BY THREATZERO SENTINEL X',
    '================================================',
  ];
  return lines.join('\n');
}

export async function encryptReport(
  report: IncidentReport,
  algorithm: CipherAlgorithm,
  passphrase: string,
): Promise<CipherReportResult> {
  const plaintext = reportToText(report);
  const hash = await sha256Hex(plaintext);

  if (algorithm === 'AES-256-GCM') {
    const payload: EncryptedPayload = await encryptEvidence(plaintext, passphrase);
    const cipherBytes = base64ToBytes(payload.ciphertext);
    const blockPreview = buildBlockPreview(plaintext, cipherBytes, 16);
    return {
      algorithm: 'AES-256-GCM',
      plaintext,
      cipherB64: payload.ciphertext,
      ivB64: payload.iv,
      saltB64: payload.salt,
      hash,
      keyBits: 256,
      blockSize: 16,
      createdAt: payload.createdAt,
      blockPreview,
      entropyScore: calcEntropy(cipherBytes),
    };
  } else {
    const result: DesResult = await desEncrypt(plaintext, passphrase);
    const cipherBytes = base64ToBytes(result.ciphertextB64);
    const blockPreview = buildBlockPreview(plaintext, cipherBytes, 8);
    return {
      algorithm: 'DES',
      plaintext,
      cipherB64: result.ciphertextB64,
      hash,
      keyBits: 56,
      blockSize: 8,
      createdAt: result.createdAt,
      blockPreview,
      entropyScore: calcEntropy(cipherBytes),
    };
  }
}

// Build a visual preview: first N blocks showing plaintext hex → ciphertext hex
function buildBlockPreview(
  plaintext: string,
  cipherBytes: Uint8Array,
  blockSize: number,
): { index: number; plainHex: string; cipherHex: string }[] {
  const plainBytes = new TextEncoder().encode(plaintext);
  const preview: { index: number; plainHex: string; cipherHex: string }[] = [];
  const maxBlocks = 8;
  for (let i = 0; i < Math.min(plainBytes.length, cipherBytes.length, blockSize * maxBlocks); i += blockSize) {
    const plainHex = Array.from(plainBytes.slice(i, i + blockSize))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join(' ');
    const cipherHex = Array.from(cipherBytes.slice(i, i + blockSize))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join(' ');
    preview.push({ index: i / blockSize, plainHex, cipherHex });
  }
  return preview;
}

// Shannon entropy of byte array (0-100 scale)
function calcEntropy(bytes: Uint8Array): number {
  if (bytes.length === 0) return 0;
  const freq = new Map<number, number>();
  for (const b of bytes) freq.set(b, (freq.get(b) || 0) + 1);
  let entropy = 0;
  for (const count of freq.values()) {
    const p = count / bytes.length;
    entropy -= p * Math.log2(p);
  }
  // Max entropy for 256 values = 8 bits → scale to 100
  return Math.round((entropy / 8) * 100);
}

// Convert cipher base64 to bytes for steganography embedding
export function cipherToBytes(result: CipherReportResult): Uint8Array {
  return base64ToBytes(result.cipherB64);
}

export { bytesToBase64 };
